-- Invite Keys
CREATE TABLE IF NOT EXISTS `invite_keys` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `key_code` VARCHAR(20) NOT NULL UNIQUE,
  `label` VARCHAR(100) DEFAULT NULL COMMENT 'Beschreibung, z.B. "Für Vertrieb Q2"',
  `max_uses` INT UNSIGNED DEFAULT NULL COMMENT 'NULL = unbegrenzt',
  `uses` INT UNSIGNED NOT NULL DEFAULT 0,
  `expires_at` TIMESTAMP NULL DEFAULT NULL,
  `created_by` INT UNSIGNED DEFAULT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
